version: "3"
services:
  node:
    image: grapefruit/mrphy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4001:4001"
    environment:
      DEVELOPMENT: "true"
    env_file:
      - .env
    volumes:
      - .:/main
