version: "3"
services:
  node:
    image: grapefruit/mrphy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    volumes:
      - .:/main
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
